# configs/default.yaml
project: shallow-water-forecast
group: EXPERIMENTS_LONG
use_fixed_seed: False
seed: 42
device: cuda
use_amp: True
save_checkpoints: True

physics_informed_loss: False
momentum_weight: 0.0
mass_weight: 0.0

use_gan: False
lambda_gp: 10.0
adv_weight: 0.1
n_critic: 5
disc_lr: 0.0001
disc_base_channels: 64

only_deltas: False
use_refiner: False
use_pretrained_convlstm: False
freeze_convlstm: False
convlstm_only_skip: False
pretrained_convlstm_path: pretrained/best_val_accuracy_model.pt
patch_size: 8
embed_dim: 256
depth: 8
num_heads: 8
mlp_ratio: 4.0
refiner_dropout: 0.001

data_dir: data/PT2
batch_size: 4
train_split: 0.8
val_split: 0.1
num_workers: 4
print_validation: True
normalize: False
skip_alpha_channel: False
hidden_channels: 64
kernel_size: 5
input_length: 5
output_length: 5
lr: 0.0001
epochs: 1000
accuracy_threshold: 0.01

optimizer: adamw
weight_decay: 0.00001

lr_scheduler: plateau
step_size: 5
gamma: 0.1
mode: min
factor: 0.5
patience: 10
T_max: 300
eta_min: 0.000000000001
min_lr: 0.000000000001

transforms:
  HorizontalFlip:
    p: 0.5
  VerticalFlip:
    p: 0.5
